(function (root) {
  'use strict';
  var SCHEMA = 'BehaviorRelationalFeatureV1';
  var FEATURES = ['TEAM_EFFECT_MARGINAL_GAIN', 'TEAM_EFFECT_REDUNDANCY_RATIO', 'RESOURCE_DEFICIT_COVERAGE', 'RESOURCE_CONSUMER_FIT', 'TEAM_FOLLOWUP_COVERAGE'];
  var TOP = ['schemaVersion', 'frozenCandidateIds', 'baselineEntries', 'candidateEntriesById', 'publicConsumers', 'baselineCompletenessByAxis', 'candidateCompletenessByAxis', 'actionCatalogCompleteness', 'sourceClosure', 'registryAttestation'];
  var REGISTRY_IDS = ['BRF_EXPLICIT_FOLLOW_UP_V1', 'BRF_NOT_RELATIONAL_V1', 'BRF_RESOURCE_SUPPLY_V1', 'BRF_TEAM_EFFECT_V1'];
  var TEAM_FIELDS = ['capabilityKind', 'ownerId', 'targetId', 'effectAxis', 'effectKey', 'timeBand', 'durationBand', 'sourceFactIds', 'sourceEventIds'];
  var SUPPLY_FIELDS = ['capabilityKind', 'ownerId', 'targetId', 'resourceKey', 'timeBand', 'supplyAmount', 'publicMaxAmount', 'sourceFactIds', 'sourceEventIds'];
  var FOLLOW_FIELDS = ['capabilityKind', 'grantType', 'ownerId', 'followUpKey', 'grantProofIds', 'sourceFactIds', 'sourceEventIds'];
  var CONSUMER_FIELDS = ['consumerId', 'ownerId', 'resourceKey', 'currentAmount', 'requiredAmount', 'actionId', 'followUpKeys', 'sourceFactIds', 'sourceEventIds'];

  function fail(code, detail) { var e = new Error(code + (detail ? ':' + detail : '')); e.code = code; throw e; }
  function object(value) { return value !== null && typeof value === 'object' && !Array.isArray(value); }
  function exact(value, fields, field) { if (!object(value)) fail('INPUT_SHAPE_FATAL', field); var allowed = Object.create(null), keys = Object.keys(value), i; for (i = 0; i < fields.length; i += 1) allowed[fields[i]] = true; for (i = 0; i < keys.length; i += 1) if (!allowed[keys[i]]) fail('INPUT_SHAPE_FATAL', field + '.' + keys[i]); }
  function has(value, key) { return Object.prototype.hasOwnProperty.call(value, key); }
  function id(value, field) { if (typeof value !== 'string' || value.length < 1 || value.length > 512 || /[\u0000-\u001f\u007f]/.test(value)) fail('INPUT_SHAPE_FATAL', field); return value; }
  function ids(value, field) { if (!Array.isArray(value)) fail('INPUT_SHAPE_FATAL', field); var seen = Object.create(null), out = [], i, item; for (i = 0; i < value.length; i += 1) { item = id(value[i], field + '[' + i + ']'); if (seen[item]) fail('DUPLICATE_IDENTITY_FATAL', field); seen[item] = true; out.push(item); } out.sort(); return out; }
  function number(value, field, positive) { if (typeof value !== 'number' || !Number.isFinite(value) || value < 0 || (positive && value <= 0)) fail('NON_FINITE_FATAL', field); return value; }
  function tupleKey(value, field) { id(value, field); var parsed; try { parsed = JSON.parse(value); } catch (error) { fail('EFFECT_KEY_FATAL', field); } if (!Array.isArray(parsed) || parsed.length !== 4) fail('EFFECT_KEY_FATAL', field); for (var i = 0; i < parsed.length; i += 1) id(parsed[i], field + '[' + i + ']'); if (JSON.stringify(parsed) !== value) fail('EFFECT_KEY_FATAL', field); return value; }
  function refs(value, field) { if (!has(value, 'sourceFactIds') || !has(value, 'sourceEventIds')) fail('SOURCE_CLOSURE_FATAL', field); var fact = ids(value.sourceFactIds, field + '.sourceFactIds'), event = ids(value.sourceEventIds, field + '.sourceEventIds'); if (fact.length === 0 && event.length === 0) fail('SOURCE_CLOSURE_FATAL', field); return { sourceFactIds: fact, sourceEventIds: event }; }
  function entry(raw, scope, seen) {
    var field = scope, kind; if (!object(raw)) fail('INPUT_SHAPE_FATAL', field); kind = id(raw.capabilityKind, field + '.capabilityKind'); var e;
    if (kind === 'TEAM_EFFECT') { exact(raw, TEAM_FIELDS, field); e = refs(raw, field); e.capabilityKind = kind; e.ownerId = id(raw.ownerId, field + '.ownerId'); e.targetId = id(raw.targetId, field + '.targetId'); e.effectAxis = id(raw.effectAxis, field + '.effectAxis'); if (!/^[A-Z][A-Z0-9_]*$/.test(e.effectAxis)) fail('INPUT_SHAPE_FATAL', field + '.effectAxis'); e.effectKey = tupleKey(raw.effectKey, field + '.effectKey'); e.timeBand = raw.timeBand; e.durationBand = raw.durationBand; if (['NOW', 'SCHEDULED'].indexOf(e.timeBand) < 0 || ['INSTANT', 'SHORT', 'MEDIUM', 'LONG', 'PERSISTENT'].indexOf(e.durationBand) < 0) fail('INPUT_SHAPE_FATAL', field + '.timeBand'); e.identity = JSON.stringify([e.targetId, e.effectAxis, e.effectKey, e.timeBand]); }
    else if (kind === 'RESOURCE_SUPPLY' && scope.indexOf('candidate') === 0) { exact(raw, SUPPLY_FIELDS, field); e = refs(raw, field); e.capabilityKind = kind; e.ownerId = id(raw.ownerId, field + '.ownerId'); e.targetId = id(raw.targetId, field + '.targetId'); e.resourceKey = id(raw.resourceKey, field + '.resourceKey'); e.timeBand = raw.timeBand; if (e.timeBand !== 'NOW' && e.timeBand !== 'SCHEDULED') fail('INPUT_SHAPE_FATAL', field + '.timeBand'); e.supplyAmount = number(raw.supplyAmount, field + '.supplyAmount', false); e.publicMaxAmount = number(raw.publicMaxAmount, field + '.publicMaxAmount', false); e.identity = JSON.stringify([e.targetId, e.resourceKey, e.timeBand, e.sourceFactIds, e.sourceEventIds]); }
    else if (kind === 'FOLLOW_UP' && scope.indexOf('candidate') === 0) { exact(raw, FOLLOW_FIELDS, field); e = refs(raw, field); e.capabilityKind = kind; if (raw.grantType !== 'FOLLOW_UP') fail('INPUT_SHAPE_FATAL', field + '.grantType'); e.grantType = 'FOLLOW_UP'; e.ownerId = id(raw.ownerId, field + '.ownerId'); e.followUpKey = id(raw.followUpKey, field + '.followUpKey'); e.grantProofIds = ids(raw.grantProofIds, field + '.grantProofIds'); if (e.grantProofIds.length === 0) fail('SOURCE_CLOSURE_FATAL', field + '.grantProofIds'); e.identity = JSON.stringify([e.ownerId, e.followUpKey]); }
    else fail('INPUT_SHAPE_FATAL', field + '.capabilityKind');
    if (seen[e.identity]) fail('DUPLICATE_IDENTITY_FATAL', field + '.identity'); seen[e.identity] = true; return e;
  }
  function entries(value, scope) { if (!Array.isArray(value)) fail('INPUT_SHAPE_FATAL', scope); var out = [], seen = Object.create(null), i; for (i = 0; i < value.length; i += 1) out.push(entry(value[i], scope + '[' + i + ']', seen)); out.sort(function (a, b) { return a.identity < b.identity ? -1 : a.identity > b.identity ? 1 : 0; }); return out; }
  function consumers(value) {
    if (!Array.isArray(value)) fail('INPUT_SHAPE_FATAL', 'publicConsumers'); var out = [], seen = Object.create(null), i, raw, field, e, consumerId;
    for (i = 0; i < value.length; i += 1) { raw = value[i]; field = 'publicConsumers[' + i + ']'; exact(raw, CONSUMER_FIELDS, field); consumerId = id(raw.consumerId, field + '.consumerId'); if (seen[consumerId]) fail('DUPLICATE_IDENTITY_FATAL', field + '.consumerId'); seen[consumerId] = true; e = refs(raw, field); e.consumerId = consumerId; e.ownerId = id(raw.ownerId, field + '.ownerId'); e.resourceKey = id(raw.resourceKey, field + '.resourceKey'); e.currentAmount = number(raw.currentAmount, field + '.currentAmount', false); e.requiredAmount = number(raw.requiredAmount, field + '.requiredAmount', true); e.actionId = id(raw.actionId, field + '.actionId'); e.followUpKeys = ids(raw.followUpKeys, field + '.followUpKeys'); e.resourceIdentity = JSON.stringify([e.ownerId, e.resourceKey]); out.push(e); }
    out.sort(function (a, b) { return a.consumerId < b.consumerId ? -1 : a.consumerId > b.consumerId ? 1 : 0; }); return out;
  }
  function completeness(value, fields, field) { exact(value, fields, field); var out = {}, i; for (i = 0; i < fields.length; i += 1) { if (value[fields[i]] !== 'COMPLETE' && value[fields[i]] !== 'PARTIAL') fail('INPUT_SHAPE_FATAL', field + '.' + fields[i]); out[fields[i]] = value[fields[i]]; } return out; }
  function set(value) { var out = Object.create(null), i; for (i = 0; i < value.length; i += 1) out[value[i]] = true; return out; }
  function closure(value) { exact(value, ['factIds', 'eventIds', 'closureHash'], 'sourceClosure'); var fact = ids(value.factIds, 'sourceClosure.factIds'), event = ids(value.eventIds, 'sourceClosure.eventIds'); if (fact.length === 0 && event.length === 0) fail('INPUT_FATAL', 'sourceClosure'); return { fact: fact, event: event, factSet: set(fact), eventSet: set(event), closureHash: id(value.closureHash, 'sourceClosure.closureHash') }; }
  function registry(value) { exact(value, ['registryVersion', 'registryHash', 'mappedCount', 'battleScopeCount', 'exactMapping', 'projectorIds'], 'registryAttestation'); if (value.registryVersion !== 'BehaviorRelationalProjectorRegistryV1' || value.registryHash !== '85016b9198590c5deb6ac4675c4f95dd7fbae164692720a087af6188e4ff6586' || value.mappedCount !== 27 || value.battleScopeCount !== 23 || value.exactMapping !== true || JSON.stringify(value.projectorIds) !== JSON.stringify(REGISTRY_IDS)) fail('REGISTRY_ATTESTATION_FATAL'); }
  function closeRecord(record, c) { var i; for (i = 0; i < record.sourceFactIds.length; i += 1) if (!c.factSet[record.sourceFactIds[i]]) fail('SOURCE_CLOSURE_FATAL', record.sourceFactIds[i]); for (i = 0; i < record.sourceEventIds.length; i += 1) if (!c.eventSet[record.sourceEventIds[i]]) fail('SOURCE_CLOSURE_FATAL', record.sourceEventIds[i]); if (record.grantProofIds) for (i = 0; i < record.grantProofIds.length; i += 1) { if (record.sourceFactIds.indexOf(record.grantProofIds[i]) < 0 && record.sourceEventIds.indexOf(record.grantProofIds[i]) < 0) fail('PROOF_FATAL', record.grantProofIds[i]); if (!c.factSet[record.grantProofIds[i]] && !c.eventSet[record.grantProofIds[i]]) fail('SOURCE_CLOSURE_FATAL', record.grantProofIds[i]); } }
  function sourceSet(records, c, includeProof) { var out = Object.create(null), i, j, r, proof; for (i = 0; i < records.length; i += 1) { r = records[i]; for (j = 0; j < r.sourceFactIds.length; j += 1) out['f:' + r.sourceFactIds[j]] = true; for (j = 0; j < r.sourceEventIds.length; j += 1) out['e:' + r.sourceEventIds[j]] = true; if (includeProof !== false && r.grantProofIds) for (j = 0; j < r.grantProofIds.length; j += 1) { proof = r.grantProofIds[j]; if (c.factSet[proof]) out['f:' + proof] = true; if (c.eventSet[proof]) out['e:' + proof] = true; } } return out; }
  function validateInput(input) {
    exact(input, TOP, 'input'); if (input.schemaVersion !== SCHEMA) fail('INPUT_SHAPE_FATAL', 'schemaVersion'); var ids0 = ids(input.frozenCandidateIds, 'frozenCandidateIds'); if (ids0.length === 0) fail('INPUT_SHAPE_FATAL', 'frozenCandidateIds'); if (!object(input.candidateEntriesById)) fail('INPUT_SHAPE_FATAL', 'candidateEntriesById'); var keys = Object.keys(input.candidateEntriesById).sort(), frozen = set(ids0), i;
    if (keys.length !== ids0.length) fail('INPUT_SHAPE_FATAL', 'candidateEntriesById'); for (i = 0; i < keys.length; i += 1) if (!frozen[keys[i]]) fail('INPUT_SHAPE_FATAL', 'candidateEntriesById'); var c = closure(input.sourceClosure), base = entries(input.baselineEntries, 'baseline'), con = consumers(input.publicConsumers), local = [], baseRefs = base.concat(con), candidateCompleteness = Object.create(null);
    for (i = 0; i < baseRefs.length; i += 1) closeRecord(baseRefs[i], c); for (i = 0; i < ids0.length; i += 1) { local.push(entries(input.candidateEntriesById[ids0[i]], 'candidate[' + ids0[i] + ']')); for (var j = 0; j < local[i].length; j += 1) closeRecord(local[i][j], c); }
    var baseComp = completeness(input.baselineCompletenessByAxis, ['TEAM_EFFECT'], 'baselineCompletenessByAxis'); exact(input.candidateCompletenessByAxis, ids0, 'candidateCompletenessByAxis'); for (i = 0; i < ids0.length; i += 1) candidateCompleteness[ids0[i]] = completeness(input.candidateCompletenessByAxis[ids0[i]], ['TEAM_EFFECT', 'RESOURCE_SUPPLY', 'FOLLOW_UP'], 'candidateCompletenessByAxis.' + ids0[i]); if (input.actionCatalogCompleteness !== 'COMPLETE' && input.actionCatalogCompleteness !== 'PARTIAL') fail('INPUT_SHAPE_FATAL', 'actionCatalogCompleteness'); registry(input.registryAttestation);
    var baseSet = sourceSet(base, c), consumerSourceMap = Object.create(null), consumer, sourceKey, sourceIds, p; for (i = 0; i < con.length; i += 1) { consumer = con[i]; sourceIds = consumer.sourceFactIds; for (j = 0; j < sourceIds.length; j += 1) { sourceKey = 'f:' + sourceIds[j]; if (!consumerSourceMap[sourceKey]) consumerSourceMap[sourceKey] = []; consumerSourceMap[sourceKey].push(consumer); } sourceIds = consumer.sourceEventIds; for (j = 0; j < sourceIds.length; j += 1) { sourceKey = 'e:' + sourceIds[j]; if (!consumerSourceMap[sourceKey]) consumerSourceMap[sourceKey] = []; consumerSourceMap[sourceKey].push(consumer); } }
    for (i = 0; i < local.length; i += 1) for (j = 0; j < local[i].length; j += 1) { var entry0 = local[i][j], candidateSet = sourceSet([entry0], c, false), sourceKeys = Object.keys(candidateSet); for (p = 0; p < sourceKeys.length; p += 1) { sourceKey = sourceKeys[p]; if (baseSet[sourceKey] || consumerSourceMap[sourceKey]) fail('SOURCE_DISJOINT_FATAL', sourceKey); } }
    return { ids: ids0, base: base, local: local, consumers: con, baseComp: baseComp, candidateComp: candidateCompleteness, catalog: input.actionCatalogCompleteness, closure: c };
  }
  function neumaier(values) { var sum = 0, correction = 0, i, next, value; for (i = 0; i < values.length; i += 1) { value = values[i]; next = sum + value; correction += Math.abs(sum) >= Math.abs(value) ? (sum - next) + value : (value - next) + sum; sum = next; } if (!Number.isFinite(sum + correction)) fail('NON_FINITE_FATAL', 'sum'); return sum + correction; }
  function recordRefs(rows, c, fallback, ordered) { var fact = Object.create(null), event = Object.create(null), list, i, j, r, p; if (!Array.isArray(rows) && rows && Array.isArray(rows.sourceFactIds) && Array.isArray(rows.sourceEventIds)) return { sourceFactIds: rows.sourceFactIds.slice(), sourceEventIds: rows.sourceEventIds.slice() }; list = rows.length ? rows : (fallback || []); for (i = 0; i < list.length; i += 1) { r = list[i]; for (j = 0; j < r.sourceFactIds.length; j += 1) fact[r.sourceFactIds[j]] = true; for (j = 0; j < r.sourceEventIds.length; j += 1) event[r.sourceEventIds[j]] = true; if (r.grantProofIds) for (j = 0; j < r.grantProofIds.length; j += 1) { p = r.grantProofIds[j]; if (c.factSet[p]) fact[p] = true; else if (c.eventSet[p]) event[p] = true; } } var factIds = Object.keys(fact), eventIds = Object.keys(event); if (!ordered) { factIds.sort(); eventIds.sort(); } return { sourceFactIds: factIds, sourceEventIds: eventIds }; }
  function operand(name, value, unit, rows, c, fallback, ordered) { var r = recordRefs(rows, c, fallback, ordered); return { name: name, value: value, unit: unit, sourceFactIds: r.sourceFactIds, sourceEventIds: r.sourceEventIds }; }
  function feature(code, status, reason, value, operands, c, fallback, ordered) { var fact = Object.create(null), event = Object.create(null), i, j, r; for (i = 0; i < operands.length; i += 1) { r = operands[i]; for (j = 0; j < r.sourceFactIds.length; j += 1) fact[r.sourceFactIds[j]] = true; for (j = 0; j < r.sourceEventIds.length; j += 1) event[r.sourceEventIds[j]] = true; } if (Object.keys(fact).length === 0 && Object.keys(event).length === 0) { r = recordRefs([], c, fallback); fact = set(r.sourceFactIds); event = set(r.sourceEventIds); } var factIds = Object.keys(fact), eventIds = Object.keys(event); if (!ordered) { factIds.sort(); eventIds.sort(); } var out = { featureCode: code, status: status, unit: 'RATIO_0_1' }; if (status === 'KNOWN') { if (!Number.isFinite(value) || value < 0 || value > 1) fail('NON_FINITE_FATAL', code); out.value = value; } out.reasonCode = reason; out.operands = operands; out.sourceFactIds = factIds; out.sourceEventIds = eventIds; return out; }
  function linkedRefs(group, count) { if (count === 0) return null; var facts = Object.create(null), events = Object.create(null), node, i; node = group.factPrefixes[count - 1]; while (node) { facts[node.id] = true; node = node.next; } node = group.eventPrefixes[count - 1]; while (node) { events[node.id] = true; node = node.next; } return { sourceFactIds: Object.keys(facts).sort(), sourceEventIds: Object.keys(events).sort() }; }
  function sharedData(base, consumers, c) {
    var fallback = [{ sourceFactIds: c.fact, sourceEventIds: c.event }], team = Object.create(null), teamRows = [], groups = Object.create(null), follow = Object.create(null), followRows = Object.create(null), initiallyRows = [], currentPayableCount = 0, i, e, key, g;
    for (i = 0; i < base.length; i += 1) { team[base[i].identity] = base[i]; teamRows.push(base[i]); }
    for (i = 0; i < consumers.length; i += 1) { e = consumers[i]; key = e.resourceIdentity; if (!groups[key]) groups[key] = { key: key, allRows: [], thresholdRows: [], thresholds: [] }; g = groups[key]; g.allRows.push(e); if (e.currentAmount < e.requiredAmount) { e.threshold = e.requiredAmount - e.currentAmount; g.thresholdRows.push(e); initiallyRows.push(e); } else currentPayableCount += 1; for (var j = 0; j < e.followUpKeys.length; j += 1) { key = JSON.stringify([e.ownerId, e.followUpKeys[j]]); if (!follow[key]) { follow[key] = true; followRows[key] = []; } followRows[key].push(e); } }
    var groupKeys = Object.keys(groups).sort(), deficitKeys = [], deficitValues = [], k, factSeen, eventSeen, node;
    for (i = 0; i < groupKeys.length; i += 1) { g = groups[groupKeys[i]]; g.thresholdRows.sort(function (a, b) { return a.threshold - b.threshold || (a.consumerId < b.consumerId ? -1 : a.consumerId > b.consumerId ? 1 : 0); }); g.currentPayableCount = g.allRows.length - g.thresholdRows.length; g.consumerRefs = recordRefs(g.allRows, c, fallback); g.initiallyRefs = recordRefs(g.thresholdRows, c, fallback); g.deficitRefs = g.initiallyRefs; factSeen = Object.create(null); eventSeen = Object.create(null); g.factPrefixes = []; g.eventPrefixes = []; for (var q = 0; q < g.thresholdRows.length; q += 1) { e = g.thresholdRows[q]; g.thresholds.push(e.threshold); node = g.factPrefixes[q - 1] || null; for (var f = 0; f < e.sourceFactIds.length; f += 1) if (!factSeen[e.sourceFactIds[f]]) { factSeen[e.sourceFactIds[f]] = true; node = { id: e.sourceFactIds[f], next: node }; } g.factPrefixes.push(node); node = g.eventPrefixes[q - 1] || null; for (var v = 0; v < e.sourceEventIds.length; v += 1) if (!eventSeen[e.sourceEventIds[v]]) { eventSeen[e.sourceEventIds[v]] = true; node = { id: e.sourceEventIds[v], next: node }; } g.eventPrefixes.push(node); }
      if (g.thresholdRows.length) { g.deficit = neumaier(g.thresholds); deficitKeys.push(groupKeys[i]); deficitValues.push(g.deficit); }
    }
    var followKeys = Object.keys(followRows).sort(), followRefs = Object.create(null); for (i = 0; i < followKeys.length; i += 1) followRefs[followKeys[i]] = recordRefs(followRows[followKeys[i]], c, fallback, true);
    return { team: team, teamKeys: Object.keys(team).sort(), teamRefs: recordRefs(teamRows, c, fallback), groups: groups, groupKeys: groupKeys, deficitKeys: deficitKeys, deficitRefs: recordRefs(initiallyRows, c, fallback), deficitTotal: neumaier(deficitValues), consumerCount: consumers.length, consumerRefs: recordRefs(consumers, c, fallback), initiallyCount: consumers.length - currentPayableCount, initiallyRefs: recordRefs(initiallyRows, c, fallback), currentPayableCount: currentPayableCount, follow: follow, followRefs: followRefs, fallback: fallback };
  }
  function localData(entries0, c) { var team = Object.create(null), teamRows = [], supplies = Object.create(null), grants = [], i, e, key; for (i = 0; i < entries0.length; i += 1) { e = entries0[i]; if (e.capabilityKind === 'TEAM_EFFECT') { team[e.identity] = e; teamRows.push(e); } else if (e.capabilityKind === 'RESOURCE_SUPPLY') { key = JSON.stringify([e.targetId, e.resourceKey]); if (!supplies[key]) supplies[key] = { nowRows: [], amount: 0, refs: null }; if (e.timeBand === 'NOW') supplies[key].nowRows.push(e); } else grants.push(e); } var supplyKeys = Object.keys(supplies).sort(), j, rows, values; for (i = 0; i < supplyKeys.length; i += 1) { rows = supplies[supplyKeys[i]].nowRows; values = []; for (j = 0; j < rows.length; j += 1) values.push(rows[j].supplyAmount); supplies[supplyKeys[i]].amount = neumaier(values); supplies[supplyKeys[i]].refs = recordRefs(rows, c); } grants.sort(function (a, b) { return a.identity < b.identity ? -1 : a.identity > b.identity ? 1 : 0; }); return { team: team, teamRows: teamRows, supplies: supplies, supplyKeys: supplyKeys, grants: grants }; }
  function upperBound(values, target) { var low = 0, high = values.length; while (low < high) { var mid = low + Math.floor((high - low) / 2); if (values[mid] <= target) low = mid + 1; else high = mid; } return low; }
  function teamFeatures(shared, local, bc, cc, c) { var bKeys = shared.teamKeys, rKeys = Object.keys(local.team).sort(), intersection = [], novel = [], i, row; for (i = 0; i < rKeys.length; i += 1) { row = local.team[rKeys[i]]; if (shared.team[rKeys[i]]) intersection.push(row, shared.team[rKeys[i]]); else novel.push(row); } function ops() { return [operand('baselineRelationCount', bKeys.length, 'COUNT', shared.teamRefs, c, shared.fallback), operand('candidateRelationCount', rKeys.length, 'COUNT', local.teamRows, c, shared.fallback), operand('intersectionCount', intersection.length / 2, 'COUNT', intersection, c, shared.fallback), operand('novelRelationCount', novel.length, 'COUNT', novel, c, shared.fallback)]; } if (bc.TEAM_EFFECT === 'PARTIAL' || cc.TEAM_EFFECT === 'PARTIAL') return [feature(FEATURES[0], 'UNKNOWN', 'AXIS_PARTIAL', null, ops(), c, shared.fallback), feature(FEATURES[1], 'UNKNOWN', 'AXIS_PARTIAL', null, ops(), c, shared.fallback)]; if (rKeys.length === 0) return [feature(FEATURES[0], 'NOT_APPLICABLE', 'NO_CANDIDATE_TEAM_EFFECT', null, ops(), c, shared.fallback), feature(FEATURES[1], 'NOT_APPLICABLE', 'NO_CANDIDATE_TEAM_EFFECT', null, ops(), c, shared.fallback)]; return [feature(FEATURES[0], 'KNOWN', 'OK', novel.length / rKeys.length, ops(), c, shared.fallback), feature(FEATURES[1], 'KNOWN', 'OK', intersection.length / 2 / rKeys.length, ops(), c, shared.fallback)]; }
  function resourceFeature(shared, local, cc, catalog, c) { var supplyRefs = [], coveredRefs = [], supplyValues = [], coveredValues = [], anyNow = false, i, key, group, supply; for (i = 0; i < local.supplyKeys.length; i += 1) { key = local.supplyKeys[i]; supply = local.supplies[key]; if (supply.nowRows.length === 0) continue; anyNow = true; group = shared.groups[key]; if (!group || !group.deficit) continue; supplyValues.push(supply.amount); coveredValues.push(Math.min(supply.amount, group.deficit)); supplyRefs.push(supply.refs); coveredRefs.push(supply.refs, group.deficitRefs); } var ops = [operand('deficitCount', shared.deficitKeys.length, 'COUNT', shared.deficitRefs, c, shared.fallback), operand('deficitTotal', shared.deficitTotal, 'ABS', shared.deficitRefs, c, shared.fallback), operand('suppliedTotal', neumaier(supplyValues), 'ABS', supplyRefs, c, shared.fallback), operand('coveredTotal', neumaier(coveredValues), 'ABS', coveredRefs, c, shared.fallback)]; if (cc.RESOURCE_SUPPLY === 'PARTIAL') return feature(FEATURES[2], 'UNKNOWN', 'AXIS_PARTIAL', null, ops, c, shared.fallback); if (shared.deficitKeys.length === 0) return feature(FEATURES[2], 'NOT_APPLICABLE', 'NO_RESOURCE_DEFICIT', null, ops, c, shared.fallback); if (!anyNow) return feature(FEATURES[2], 'NOT_APPLICABLE', 'NO_RESOURCE_SUPPLY', null, ops, c, shared.fallback); return feature(FEATURES[2], 'KNOWN', 'OK', neumaier(coveredValues) / shared.deficitTotal, ops, c, shared.fallback); }
  function consumerFeature(shared, local, cc, catalog, c) { var newlyRefs = [], axisConsumerRefs = [], axisInitialRefs = [], newlyCount = 0, axisCount = 0, initiallyCount = 0, hasAxis = false, i, key, supply, group, count, prefix; for (i = 0; i < local.supplyKeys.length; i += 1) { key = local.supplyKeys[i]; supply = local.supplies[key]; group = shared.groups[key]; if (!group) continue; hasAxis = true; axisCount += group.allRows.length; initiallyCount += group.allRows.length - group.currentPayableCount; axisConsumerRefs.push(group.consumerRefs); axisInitialRefs.push(group.initiallyRefs); if (supply.nowRows.length === 0) continue; count = upperBound(group.thresholds, supply.amount); newlyCount += count; if (supply.refs) newlyRefs.push(supply.refs); prefix = linkedRefs(group, count); if (prefix) newlyRefs.push(prefix); } var consumerCount = hasAxis ? axisCount : shared.consumerCount, initialCount = hasAxis ? initiallyCount : shared.initiallyCount, consumerRefs = hasAxis ? axisConsumerRefs : shared.consumerRefs, initialRefs = hasAxis ? axisInitialRefs : shared.initiallyRefs; var ops = [operand('consumerCount', consumerCount, 'COUNT', consumerRefs, c, shared.fallback), operand('initiallyUnpayableCount', initialCount, 'COUNT', initialRefs, c, shared.fallback), operand('newlyPayableCount', newlyCount, 'COUNT', newlyRefs, c, shared.fallback)]; if (cc.RESOURCE_SUPPLY === 'PARTIAL') return feature(FEATURES[3], 'UNKNOWN', 'AXIS_PARTIAL', null, ops, c, shared.fallback); if (consumerCount === 0) return feature(FEATURES[3], 'NOT_APPLICABLE', 'NO_RESOURCE_CONSUMER', null, ops, c, shared.fallback); return feature(FEATURES[3], 'KNOWN', 'OK', newlyCount / consumerCount, ops, c, shared.fallback); }
  function followupFeature(shared, local, cc, catalog, c) { var bound = [], matched = 0, i, grant, key; for (i = 0; i < local.grants.length; i += 1) { grant = local.grants[i]; key = JSON.stringify([grant.ownerId, grant.followUpKey]); if (shared.follow[key]) { matched += 1; bound.push(grant, shared.followRefs[key]); } } var ops = [operand('grantCount', local.grants.length, 'COUNT', local.grants, c, shared.fallback, true), operand('consumerBoundGrantCount', matched, 'COUNT', bound, c, shared.fallback, true)]; if (catalog === 'PARTIAL' || cc.FOLLOW_UP === 'PARTIAL') return feature(FEATURES[4], 'UNKNOWN', catalog === 'PARTIAL' ? 'ACTION_CATALOG_PARTIAL' : 'AXIS_PARTIAL', null, ops, c, shared.fallback, true); if (local.grants.length === 0) return feature(FEATURES[4], 'NOT_APPLICABLE', 'NO_FOLLOW_UP_GRANT', null, ops, c, shared.fallback, true); return feature(FEATURES[4], 'KNOWN', 'OK', matched / local.grants.length, ops, c, shared.fallback, true); }
  function freeze(value) { if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value; Object.freeze(value); var keys = Object.keys(value), i; for (i = 0; i < keys.length; i += 1) freeze(value[keys[i]]); return value; }
  function compileDecision(input) { var data = validateInput(input), shared = sharedData(data.base, data.consumers, data.closure), order = data.ids.slice().sort(), byId = Object.create(null), out = [], i, id0, local, cc, team; for (i = 0; i < data.ids.length; i += 1) byId[data.ids[i]] = data.local[i]; for (i = 0; i < order.length; i += 1) { id0 = order[i]; local = localData(byId[id0], data.closure); cc = data.candidateComp[id0]; team = teamFeatures(shared, local, data.baseComp, cc, data.closure); out.push({ candidateId: id0, features: [team[0], team[1], resourceFeature(shared, local, cc, data.catalog, data.closure), consumerFeature(shared, local, cc, data.catalog, data.closure), followupFeature(shared, local, cc, data.catalog, data.closure)] }); } return freeze({ schemaVersion: SCHEMA, perCandidate: out }); }
  root.__LWCS_BEHAVIOR_RELATIONAL_FEATURE__ = Object.freeze({ compileDecision: compileDecision });
})(typeof globalThis === 'object' ? globalThis : this);
