export const manualBattleCases = Object.freeze([
  { caseId: 'duel_overmatch_lethal', group: 'duel', rounds: 20, focus: ['level_gap', 'lethal_intent'] },
  { caseId: 'duel_overmatch_nonlethal', group: 'duel', rounds: 20, focus: ['level_gap', 'nonlethal_intent'] },
  { caseId: 'duel_underdog_survival', group: 'duel', rounds: 20, focus: ['underdog', 'survival'] },
  { caseId: 'duel_peer_unknown_probe', group: 'duel', rounds: 20, focus: ['peer', 'limited_information'] },
  { caseId: 'duel_agile_single_target_failure', group: 'duel', rounds: 20, focus: ['agile', 'adaptation'] },
  { caseId: 'duel_agile_counter_options', group: 'duel', rounds: 20, focus: ['agile', 'counterplay'] },
  { caseId: 'duel_charge_interrupt_safer', group: 'duel', rounds: 20, focus: ['charging', 'interrupt'] },
  { caseId: 'duel_charge_defense_safer', group: 'duel', rounds: 20, focus: ['charging', 'defense'] },
  { caseId: 'team_focus_without_overkill', group: 'team', rounds: 10, focus: ['focus', 'overkill'] },
  { caseId: 'team_protect_critical_ally', group: 'team', rounds: 10, focus: ['protect', 'ally_crisis'] },
  { caseId: 'team_heal_crisis', group: 'team', rounds: 10, focus: ['healing', 'ally_crisis'] },
  { caseId: 'team_control_overlap', group: 'team', rounds: 10, focus: ['control', 'marginal_value'] },
  { caseId: 'team_resource_support', group: 'team', rounds: 10, focus: ['resource', 'consumer'] },
  { caseId: 'team_multi_target_response', group: 'team', rounds: 10, focus: ['aoe', 'targeting'] },
  { caseId: 'team_counter_coordination', group: 'team', rounds: 10, focus: ['counter', 'coordination'] },
  { caseId: 'team_unknown_enemy_adaptation', group: 'team', rounds: 10, focus: ['limited_information', 'adaptation'] },
  { caseId: 'raid_balanced', group: 'raid', rounds: 5, focus: ['balanced', 'seven_vs_seven'] },
  { caseId: 'raid_level_gap', group: 'raid', rounds: 5, focus: ['level_gap', 'seven_vs_seven'] },
  { caseId: 'raid_control_heavy', group: 'raid', rounds: 5, focus: ['control', 'seven_vs_seven'] },
  { caseId: 'raid_summon_heavy', group: 'raid', rounds: 5, focus: ['summon', 'seven_vs_seven'] },
  { caseId: 'summon_one_window', group: 'special', rounds: 6, focus: ['summon', 'lifecycle'] },
  { caseId: 'item_creation_consumption', group: 'special', rounds: 8, focus: ['creation', 'inventory', 'consumer'] },
  { caseId: 'equipment_switch_no_loop', group: 'special', rounds: 8, focus: ['equipment', 'loop_prevention'] },
  { caseId: 'intent_capture_vs_kill', group: 'special', rounds: 8, focus: ['battle_intent', 'terminal'] },
]);

export const determinismCaseIds = Object.freeze([
  'duel_overmatch_lethal',
  'team_control_overlap',
  'raid_balanced',
  'summon_one_window',
  'item_creation_consumption',
]);
