export const battleR63ManualReviewNotes = Object.freeze({
  duel_overmatch_lethal: {
    behavior: '符合等级压制常识：高等级方的普通攻击已经足以形成终结，不需要为了展示技能而浪费动作。',
    narrative: '战报正确表现为单方先手命中并结束战斗；没有虚构低等级方后续行动。',
    anomalies: '单回合结束不是漏行动，而是目标已失去战斗能力。',
    alternatives: '若目标存在非致命或任务约束，才应改用限伤或控制；本案例没有该约束。',
    responsibility: '无',
    blocking: false,
  },
  duel_overmatch_nonlethal: {
    behavior: '符合点到为止：高等级方仍可使用高收益技能，但正式结算将目标保留在1点生命，未把非致命约束误判为必须空过。',
    narrative: '战报保留技能、命中、限伤终态和控制状态；回合在意图终态达成后结束。',
    anomalies: '没有双方对打的后续回合，这是非致命终态停止规则造成的，不是候选缺失。',
    alternatives: '普通攻击或低伤控制也可成立，但当前技能在非致命限伤下仍是有效压制。',
    responsibility: '无',
    blocking: false,
  },
  duel_underdog_survival: {
    behavior: '弱者在强者蓄力尚未完成时先用控制/削弱试探，随后强者完成蓄力并造成高额伤害，符合等级差和蓄力窗口常识。',
    narrative: '战报能区分弱者前两次动作、强者蓄力完成和最终命中；没有把蓄力过程写成无原因待机。',
    anomalies: '弱者最终没有撑过高等级蓄力命中，说明求生动作不是保证生还。',
    alternatives: '撤退或更高优先级打断可作为变体，不能要求弱者在明显等级差下必然成功。',
    responsibility: '无',
    blocking: false,
  },
  duel_peer_unknown_probe: {
    behavior: '低置信度下，韦小枫用兼具控制与协同追击的青影蛇群试探谢邂的反应；前两次控制成立且召唤拥有真实行动窗口，继续使用仍有边际收益，资源不足后自然退回普通攻击。谢邂始终选择当前更高收益的普通攻击。',
    narrative: '宿主声明、控制成败、召唤生成、追击、消散和双方反应分别有事实；没有把协同伤害写成宿主技能直接伤害。',
    anomalies: '公开观察与置信度确实更新，但本场动作变化同时受魂力可支付性影响，单独不足以证明“失败后因后验变化改招”的强适应性。',
    alternatives: '若首次控制连续失败且资源仍足以重试，后续应由Beta后验自然降低该动作价值；该反事实需在Phase 11适应性专项继续盲审。',
    responsibility: 'BattleDecision适应性专项覆盖（Phase 11）',
    blocking: false,
  },
  duel_agile_single_target_failure: {
    behavior: '濒死单位选择撤退而非继续攻击；撤退因撤离分低于追击分失败，敌方追击伤害单独结算，符合弱势敏攻系无法甩脱强追击者的常识。',
    narrative: '战报明确区分撤退失败、撤离追击和实际伤害，没有把无伤撤退动作伪造成直接伤害。',
    anomalies: '该案例验证的是合理求生选择可能失败，不是撤退必定成功。',
    alternatives: '若存在高命中反杀技能或控制窗口，攻击/控制可以成为合理替代。',
    responsibility: '无',
    blocking: false,
  },
  duel_agile_counter_options: {
    behavior: '首回合王金玺成功主动闪避并打开40%防反窗口，新COUNTER决策选择普通攻击造成55点伤害；谢邂获得独立二次闪避决策但未成功。随后双方按命中与闪避结果继续自然行动。',
    narrative: '主动攻击、首次闪避、防反窗口、反击命中和二次闪避位于同一因果动作组，55点伤害只由唯一hit_result承载。',
    anomalies: '双方现有魂技在客观效用上均被普通攻击支配，因此五回合主要使用普通攻击；这是当前原型数值结果，不是轮换或重复惩罚。',
    alternatives: '当魂技获得更高有效伤害、控制窗口或防反专用授权时应自然进入反击候选，不设置固定反击技能。',
    responsibility: '无',
    blocking: false,
  },
  duel_charge_interrupt_safer: {
    behavior: '面对显露蓄力优先打断，而不是继续贪伤害；打断成功后保留打断反噬和后续行动，不免费赠送连击。',
    narrative: '战报记录蓄力被打断、状态和反噬来源，未把控制直接写成额外攻击。',
    anomalies: '后续回合重新决策属于蓄力者仍存活后的自然行动。',
    alternatives: '若打断途中会被蓄力技能先结算，防御或等待反击可以胜出。',
    responsibility: '无',
    blocking: false,
  },
  duel_charge_defense_safer: {
    behavior: '第一回合蓄力尚需跨过下一自然行动，提前闪避会在攻击到来前过期，因此韦小枫只做低收益普通攻击；第二回合来袭已进入防守窗口寿命，韦小枫才建立闪避姿态并在第三回合消费。',
    narrative: '战报区分蓄力倒计时、普通攻击、姿态建立、姿态消费与蓄力命中，没有把蓄力过程写成无原因待机。',
    anomalies: '面对显著等级差，闪避姿态仍未保证规避，点到为止终态令韦小枫保留1点生命并失去战斗能力。',
    alternatives: '若资源足以支持可靠打断，打断可以胜出；若防守窗口会提前过期，则不能为了“看起来谨慎”而过早防守。',
    responsibility: '无',
    blocking: false,
  },
  team_focus_without_overkill: {
    behavior: '唐舞麟在首轮遭先手击倒后不再产生行动；谢邂与古月共同压低张扬子，张扬子第三回合建立闪避仍被谢邂终结，古月随后转向韦小枫，第四回合双方再按剩余容量转火王金玺/古月，没有鞭尸。',
    narrative: '主动攻击、召唤生成、召唤追击和目标变化均有独立事实。',
    anomalies: '首轮唐舞麟未行动来自真实死亡终态而非漏行动；部分召唤兜底改打合法集火目标后未命中，属于结算结果。',
    alternatives: '目标进入斩杀线后可转火，不能为了保持集火文案继续攻击同一目标。',
    responsibility: '无',
    blocking: false,
  },
  team_protect_critical_ally: {
    behavior: '雅莉首轮先治疗并加盾，使5%生命的舞长空承受三名敌人集火后仍能行动；边际下降时雅莉转为攻击，第二轮舞长空再次进入危机后第三轮重新治疗。保护动作随真实缺口变化，没有职责轮换。',
    narrative: '治疗、净化无目标、三人护盾、护盾吸收/破碎、装备锁血、后续攻击和再次治疗均来自Ledger；没有把攻击文案伪装成保护。',
    anomalies: '敌方持续合理集火舞长空，舞长空依靠护盾、闪避和装备护主存活；本场没有任何队友被错误漏掉或无原因死亡。',
    alternatives: '治疗、护盾、群控和击杀威胁均可成为保护动作，取决于预计回应前的容量损失。',
    responsibility: '无',
    blocking: false,
  },
  team_heal_crisis: {
    behavior: '雅莉首轮对两名受伤队友完成群体治疗并为三人加盾，护盾实际吸收随后群攻；边际下降后雅莉凭等级优势改用普通攻击压低苏沐/龙跃，未在满血与完整护盾上机械重复治疗。',
    narrative: '护盾、状态、资源和后续攻击均被保留，治疗不是一句无数值描述。',
    anomalies: '雅莉普通攻击伤害显著高于队友来自真实等级差；这不否定首轮危机支援，但后续仍需用同等级治疗者变体保护职责边界。',
    alternatives: '若敌方有即将完成的蓄力终结，打断可能优于治疗。',
    responsibility: '无',
    blocking: false,
  },
  team_control_overlap: {
    behavior: '许小言优先分配单体控制给苏沐/戴月炎，舞长空使用群体迟缓与位移限制覆盖不同窗口；后续根据状态到期和目标边际在霜冰语、霜雾与凝霜间变化，没有对同一未过期硬控机械重叠，也没有免费追加攻击。',
    narrative: '群控、抗性、伤害、蓄力重击和资源恢复均能从事实链追溯。',
    anomalies: '状态类动作在展示层仍偏碎片化，属于后续战报聚合工作，不影响本轮事实闭环。',
    alternatives: '对免控目标应转为伤害、破盾或等待真实反击窗口。',
    responsibility: 'BattleRuntime report projection（后续Phase 10）',
    blocking: false,
  },
});
